---
title: "2° Investing Initiative"
output: html_document
---

# About 2° Investing Initiative

## We align financial markets with climate goals

The 2° Investing Initiative (2DII) is an independent, non-profit think tank working to align financial markets and regulations with the Paris Agreement goals. Globally focused with offices in Paris, New York, Berlin, London, and Brussels, 2DII coordinates some of the world’s largest research projects on sustainable finance. Its team of finance, climate, and risk experts develop research, tools, and policy insights to help financial institutions and regulators hasten and adapt to the low-carbon transition. In addition to its hubs in Europe and the US, 2DII has a special focus on emerging markets, with active research projects across Latin America, Asia, and Africa.

Find out more on https://2degrees-investing.org/

## Research programs

### PACTA / Climate Scenario Analysis Program

One of the long-term objectives of the Paris Agreement is making finance consistent with climate goals. The PACTA climate scenario analysis methodology helps financial institutions and regulators contribute to this objective, enabling them to assess the alignment of their portfolios with climate benchmarks and steer towards a ‘greener’ pathway. Already, more than 3,000 financial institutions worldwide have used PACTA, in addition to major supervisors and central banks (EIOPA, California Department of Insurance, Bank of England, and more).

### Retail Investing Program

2° Investing Initiative’s Retail Investing Program employs data-driven research, legal analysis, product development, and communications tools to integrate sustainability into the retail investing market. Our mission is to help reallocate individual savings to finance the low-carbon transition, as well as to align retail investing industry practices with the Paris Agreement goals. To achieve this, we focus on supporting retail investors in their efforts to invest sustainably; helping financial institutions improve the sustainability of their product offering; and devising policy recommendations for governments and regulators, with a special focus on Europe.

### 1in1000 Program on Future Risks & Challenges

1in1000 is a new research program by 2° Investing Initiative that helps financial institutions and supervisors address future risks and challenges, especially those related to climate change. The program aims to integrate risks posed by climate change, ecosystem service and biodiversity loss, and the breakdown of social cohesion into financial processes and regulations. It focuses on developing long-term risk metrics, designing risk management tools and frameworks, and building capacity for financial institutions and supervisors. Find out more at www.1in1000.com.

### Impact Program

Since COP21, climate target-setting by investors and banks has evolved into an increasingly popular concept. However, the lack of standardized frameworks and best practices in this field is emerging as a major obstacle to the alignment of global financial flows with the Paris Agreement goals. To address this issue, 2° Investing Initiative is working closely with financial institutions, policymakers, and other stakeholders across the sustainable finance sector in order to develop enhanced methodologies on impact and target-setting.

## Our values

### Non-commercial & committed to the public good
We have no commercial contracts and provide all of our research open source and IP rights-free. This policy minimizes financial conflicts of interest and guarantees the public good-driven nature of our work.

### Independent and interest-neutral
Our governance and our funding structure is designed to be diversified and multi-stakeholder. This helps ensure that our research does not represent a particular interest group, but rather our best understanding of the truth.

### Science- and evidence-based
We continuously aim to expand and improve the evidence base for decision-making in sustainable finance.

